logging:
  file:
    name: library-ws.log
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 3000
spring:
  datasource:
    password: Pass@1234
    url: jdbc:mysql://localhost:3306/hr
    username: root
  jpa:
    #hibernate:
     # ddl-auto: create
    show-sql: true
